{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Inport your location"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting geopy\n",
      "  Downloading https://files.pythonhosted.org/packages/f3/b4/c8842fc6a07fc95d6887370768850885382b47bf52f5cd8b6a4ae1b6f4d9/geopy-1.17.0-py2.py3-none-any.whl (92kB)\n",
      "Collecting geographiclib<2,>=1.49 (from geopy)\n",
      "  Downloading https://files.pythonhosted.org/packages/5b/ac/4f348828091490d77899bc74e92238e2b55c59392f21948f296e94e50e2b/geographiclib-1.49.tar.gz\n",
      "Building wheels for collected packages: geographiclib\n",
      "  Running setup.py bdist_wheel for geographiclib: started\n",
      "  Running setup.py bdist_wheel for geographiclib: finished with status 'done'\n",
      "  Stored in directory: C:\\Users\\Zeguan\\AppData\\Local\\pip\\Cache\\wheels\\99\\45\\d1\\14954797e2a976083182c2e7da9b4e924509e59b6e5c661061\n",
      "Successfully built geographiclib\n",
      "Installing collected packages: geographiclib, geopy\n",
      "Successfully installed geographiclib-1.49 geopy-1.17.0\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "You are using pip version 10.0.1, however version 18.1 is available.\n",
      "You should consider upgrading via the 'python -m pip install --upgrade pip' command.\n"
     ]
    }
   ],
   "source": [
    "!pip install geopy --upgrade"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting shapely\n",
      "  Using cached https://files.pythonhosted.org/packages/a2/fb/7a7af9ef7a35d16fa23b127abee272cfc483ca89029b73e92e93cdf36e6b/Shapely-1.6.4.post2.tar.gz\n",
      "    Complete output from command python setup.py egg_info:\n",
      "    Traceback (most recent call last):\n",
      "      File \"<string>\", line 1, in <module>\n",
      "      File \"C:\\Users\\Zeguan\\AppData\\Local\\Temp\\pip-install-jgl4yls6\\shapely\\setup.py\", line 80, in <module>\n",
      "        from shapely._buildcfg import geos_version_string, geos_version, \\\n",
      "      File \"C:\\Users\\Zeguan\\AppData\\Local\\Temp\\pip-install-jgl4yls6\\shapely\\shapely\\_buildcfg.py\", line 200, in <module>\n",
      "        lgeos = CDLL(\"geos_c.dll\")\n",
      "      File \"D:\\Programs\\Anaconda3\\lib\\ctypes\\__init__.py\", line 348, in __init__\n",
      "        self._handle = _dlopen(self._name, mode)\n",
      "    OSError: [WinError 126] The specified module could not be found\n",
      "    \n",
      "    ----------------------------------------\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Command \"python setup.py egg_info\" failed with error code 1 in C:\\Users\\Zeguan\\AppData\\Local\\Temp\\pip-install-jgl4yls6\\shapely\\\n",
      "You are using pip version 10.0.1, however version 18.1 is available.\n",
      "You should consider upgrading via the 'python -m pip install --upgrade pip' command.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already up-to-date: geojsonio in d:\\programs\\anaconda3\\lib\\site-packages (0.0.3)\n",
      "Requirement not upgraded as not directly required: github3.py in d:\\programs\\anaconda3\\lib\\site-packages (from geojsonio) (1.2.0)\n",
      "Requirement not upgraded as not directly required: six in d:\\programs\\anaconda3\\lib\\site-packages (from geojsonio) (1.11.0)\n",
      "Requirement not upgraded as not directly required: uritemplate>=3.0.0 in d:\\programs\\anaconda3\\lib\\site-packages (from github3.py->geojsonio) (3.0.0)\n",
      "Requirement not upgraded as not directly required: jwcrypto>=0.5.0 in d:\\programs\\anaconda3\\lib\\site-packages (from github3.py->geojsonio) (0.6.0)\n",
      "Requirement not upgraded as not directly required: requests>=2.18 in d:\\programs\\anaconda3\\lib\\site-packages (from github3.py->geojsonio) (2.18.4)\n",
      "Requirement not upgraded as not directly required: python-dateutil>=2.6.0 in d:\\programs\\anaconda3\\lib\\site-packages (from github3.py->geojsonio) (2.7.3)\n",
      "Requirement not upgraded as not directly required: cryptography>=1.5 in d:\\programs\\anaconda3\\lib\\site-packages (from jwcrypto>=0.5.0->github3.py->geojsonio) (2.2.2)\n",
      "Requirement not upgraded as not directly required: chardet<3.1.0,>=3.0.2 in d:\\programs\\anaconda3\\lib\\site-packages (from requests>=2.18->github3.py->geojsonio) (3.0.4)\n",
      "Requirement not upgraded as not directly required: idna<2.7,>=2.5 in d:\\programs\\anaconda3\\lib\\site-packages (from requests>=2.18->github3.py->geojsonio) (2.6)\n",
      "Requirement not upgraded as not directly required: urllib3<1.23,>=1.21.1 in d:\\programs\\anaconda3\\lib\\site-packages (from requests>=2.18->github3.py->geojsonio) (1.22)\n",
      "Requirement not upgraded as not directly required: certifi>=2017.4.17 in d:\\programs\\anaconda3\\lib\\site-packages (from requests>=2.18->github3.py->geojsonio) (2018.4.16)\n",
      "Requirement not upgraded as not directly required: asn1crypto>=0.21.0 in d:\\programs\\anaconda3\\lib\\site-packages (from cryptography>=1.5->jwcrypto>=0.5.0->github3.py->geojsonio) (0.24.0)\n",
      "Requirement not upgraded as not directly required: cffi>=1.7 in d:\\programs\\anaconda3\\lib\\site-packages (from cryptography>=1.5->jwcrypto>=0.5.0->github3.py->geojsonio) (1.11.5)\n",
      "Requirement not upgraded as not directly required: pycparser in d:\\programs\\anaconda3\\lib\\site-packages (from cffi>=1.7->cryptography>=1.5->jwcrypto>=0.5.0->github3.py->geojsonio) (2.18)\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "You are using pip version 10.0.1, however version 18.1 is available.\n",
      "You should consider upgrading via the 'python -m pip install --upgrade pip' command.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already up-to-date: folium in d:\\programs\\anaconda3\\lib\\site-packages (0.7.0)\n",
      "Requirement not upgraded as not directly required: six in d:\\programs\\anaconda3\\lib\\site-packages (from folium) (1.11.0)\n",
      "Requirement not upgraded as not directly required: branca>=0.3.0 in d:\\programs\\anaconda3\\lib\\site-packages (from folium) (0.3.1)\n",
      "Requirement not upgraded as not directly required: jinja2 in d:\\programs\\anaconda3\\lib\\site-packages (from folium) (2.10)\n",
      "Requirement not upgraded as not directly required: numpy in d:\\programs\\anaconda3\\lib\\site-packages (from folium) (1.14.3)\n",
      "Requirement not upgraded as not directly required: requests in d:\\programs\\anaconda3\\lib\\site-packages (from folium) (2.18.4)\n",
      "Requirement not upgraded as not directly required: MarkupSafe>=0.23 in d:\\programs\\anaconda3\\lib\\site-packages (from jinja2->folium) (1.0)\n",
      "Requirement not upgraded as not directly required: chardet<3.1.0,>=3.0.2 in d:\\programs\\anaconda3\\lib\\site-packages (from requests->folium) (3.0.4)\n",
      "Requirement not upgraded as not directly required: idna<2.7,>=2.5 in d:\\programs\\anaconda3\\lib\\site-packages (from requests->folium) (2.6)\n",
      "Requirement not upgraded as not directly required: urllib3<1.23,>=1.21.1 in d:\\programs\\anaconda3\\lib\\site-packages (from requests->folium) (1.22)\n",
      "Requirement not upgraded as not directly required: certifi>=2017.4.17 in d:\\programs\\anaconda3\\lib\\site-packages (from requests->folium) (2018.4.16)\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "You are using pip version 10.0.1, however version 18.1 is available.\n",
      "You should consider upgrading via the 'python -m pip install --upgrade pip' command.\n"
     ]
    }
   ],
   "source": [
    "import json\n",
    "from Dinner_Function import dinner\n",
    "import Visualization\n",
    "#Import clusters data\n",
    "with open('clusters.json','rb') as clusters_init:\n",
    "    clusters_data = json.loads(clusters_init.read())\n",
    "#import clusters center\n",
    "with open('clusters_centers.json','rb') as clusters_coordinates:\n",
    "    clusters_coordinates = json.loads(clusters_coordinates.read())"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "person_address = input('Input your location:')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [],
   "source": [
    "import requests\n",
    "address = person_address.replace(' ','+')\n",
    "response = requests.get('https://maps.googleapis.com/maps/api/geocode/json?address=%s&key=AIzaSyBmpmNHzWutfb5CY7K3PeZZbvU4KAld3rM'%address)\n",
    "resp_json_payload = response.json()\n",
    "\n",
    "person_site = [resp_json_payload['results'][0]['geometry']['location']['lat'],\n",
    "              resp_json_payload['results'][0]['geometry']['location']['lng']]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [],
   "source": [
    "results = dinner(person_site,clusters_coordinates, clusters_data)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [
    {
     "ename": "TypeError",
     "evalue": "__init__() got an unexpected keyword argument 'color'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mTypeError\u001b[0m                                 Traceback (most recent call last)",
      "\u001b[1;32m<ipython-input-5-9637714db4bb>\u001b[0m in \u001b[0;36m<module>\u001b[1;34m()\u001b[0m\n\u001b[1;32m----> 1\u001b[1;33m \u001b[0mVisualization\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mResultsVisualization\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mresults\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m",
      "\u001b[1;32mD:\\Files\\Columbia University\\Course\\IEOR 4501 Tools for Analytics Python\\Github\\The-cleverest-guy-in-this-planet\\Visualization.py\u001b[0m in \u001b[0;36mResultsVisualization\u001b[1;34m(results)\u001b[0m\n\u001b[0;32m     74\u001b[0m             \u001b[0mlocation\u001b[0m\u001b[1;33m=\u001b[0m\u001b[1;33m[\u001b[0m\u001b[0mlat\u001b[0m\u001b[1;33m,\u001b[0m\u001b[0mlon\u001b[0m\u001b[1;33m]\u001b[0m\u001b[1;33m,\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m     75\u001b[0m             \u001b[0mpopup\u001b[0m\u001b[1;33m=\u001b[0m\u001b[0mpopup\u001b[0m\u001b[1;33m,\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m---> 76\u001b[1;33m             color=col).add_to(m)\n\u001b[0m\u001b[0;32m     77\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m     78\u001b[0m     \u001b[1;32mreturn\u001b[0m \u001b[0mm\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;31mTypeError\u001b[0m: __init__() got an unexpected keyword argument 'color'"
     ]
    }
   ],
   "source": [
    "Visualization.ResultsVisualization(results)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
